### ISSUE TITLE
Prerequisites listing missing JDK version

### ISSUE THREAD

**Issue by jackn11** [vaticle/biograkn-covid#22]
I got the error "...has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0" when running ```./typedb server``` on Windows 10 due to an outdated version of JDK. However, a version of JDK is not listed in the prerequisites section in the readme for typedb-bio. I suggest that JDK version >= 11 be added to the list of prerequisites.

**Comment by james-whiteside** [comment]
Actioned.
