### ISSUE TITLE
Non-returning queries

### ISSUE THREAD

**Issue by hskaushik** [vaticle/biograkn-covid#4]
I tried executing example queries provided inside the directory "Query Examples".  But, the query did not return anything. I am still new to grakn and graql and probably missing something obvious. Can someone please help me understand?

I am using workbase 1.3.1 and grakn 1.8

Thanks,
Kaushik

**Comment by tomassabat** [comment]
Hi Kaushik! I'm sorry we should have mentioned that the schema had changed but we didn't update the example queries yet. We've removed the directory for now, but there's two example queries in the Read me now.
